### ISSUE TITLE
kinect2_bridge_nodelet issues

### ISSUE THREAD

**Issue by pinkki** [Soy-Robotics/Ros2Bot#2]
Hello! I am using turtlebot2 with kinect2.

I have installed & configured the libfreenect and the kinect2bridge successfully before. And I prompted to use your solution to use "navigation" on the turtlebot2 with kinect2.

I have followed your steps to copy the files to the specific places but when I launch the "roslaunch turtlebot_navigation gmapping_kinect2_opengl.launch" , the errors occurs as below: 

```
[ INFO] [1460700235.209242631]: Using plugin "static_layer"
[ INFO] [1460700235.480002162]: Requesting the map...
[ERROR] [1460700236.768612683]: Failed to load nodelet [/kinect2_bridge] of type [kinect2_bridge/kinect2_bridge_nodelet] even after refreshing the cache: Could not find library corresponding to plugin kinect2_bridge/kinect2_bridge_nodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1460700236.768681110]: The error before refreshing the cache was: Could not find library corresponding to plugin kinect2_bridge/kinect2_bridge_nodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1460700236.769027446]: Service call failed!
[kinect2_bridge-2] process has died [pid 6531, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load kinect2_bridge/kinect2_bridge_nodelet kinect2 __name:=kinect2_bridge __log:=/home/sun/.ros/log/b9e28048-02ce-11e6-8894-24fd52c570d7/kinect2_bridge-2.log].
log file: /home/sun/.ros/log/b9e28048-02ce-11e6-8894-24fd52c570d7/kinect2_bridge-2*.log

```

Would u please help me?

**Comment by vishu2287** [comment]
@pinkki 
May i know your system configuration? are you using jetson board or PC?
Have you tried to run kinect2_bridge alone? 
"roslaunch kinect2_bridge kinect2_bridge.launch "
and "rosrun kinect2_viewer kinect2_viewer" ?

**Comment by pinkki** [comment]
@vishu2287 I am using ubuntu14.04.4 on a PC, the distribution of ROS is indigo.

**Comment by pinkki** [comment]
@vishu2287 
I had tried run kinect2_bridge alone before I followed the steps to change the files and it worked successfully.
But after I changed the files , it doesn't work and the errors are the same to the errors I showed which is caused by "navigation" .

**Comment by Soy-Robotics** [comment]
I will close this issues due to long time.
